const Article = (props) => {
    return(
        <article>
            <h4>Title of news Article{props.number}</h4>
            <p>Published {props.published}</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id aliquam numquam quaerat tempora ducimus blanditiis odit aperiam ipsam sequi dignissimos veniam iusto libero reiciendis velit, optio autem magni animi ipsum.</p>
        </article>
    )
}

export default Article;